spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benstitou/spring-microservices-kafka-demo
          search-paths:
            - "ms-config-properties/{application}/{profile}"
